### ISSUE TITLE
Alterar ambiente ativo quando trocar projeto

### ISSUE THREAD

**Issue by PAULOCAMATA** [AlencarGabriel/advpl-switch-project#14]
Caso o projeto possua configuração de ambientes, ao trocar o projeto deverá ser verificado se o novo projeto selecionado possui o ambiente que está selecionado atualmente. Caso não possua deverá ser selecionado o primeiro da lista dos ambientes disponíveis para aquele projeto.

**Comment by AlencarGabriel** [comment]
Alterado para sempre que um projeto for trocado, a extensão irá trocar para o primeiro ambiente ativo;
