### ISSUE TITLE
Opção de exibir todos os projetos

### ISSUE THREAD

**Issue by AugustoPontin** [AlencarGabriel/advpl-switch-project#16]
Gostaria de ter a opção de em certo momento exibir todos os projetos que foram ocultados pela extensão, pois as vezes preciso procurar algum determinado texto em todos os projetos e o VSCode só pesquisa no projeto filtrado pela extensão.

**Comment by AlencarGabriel** [comment]
Melhorado comandos para habilitar/desabilitar todos os projetos integrando com a troca de ambientes;
