### ISSUE TITLE
Duplicando projeto no Workspace Settings

### ISSUE THREAD

**Issue by AlencarGabriel** [AlencarGabriel/advpl-switch-project#6]
Ao selecionar um projeto está  duplicando no Workspace Settings.

**Comment by jcstorino** [comment]
Muito boa a idéia da extensão... reparei que quando eu seleciono um novo projeto ele mantém o anterior aberto e adiciona no settings a nova folder.. mas quando tento mudar o projeto novamente avisa que tenho que rodar um comando para limpar as outras pastas abertas...

![image](https://user-images.githubusercontent.com/19559870/46831311-7c015880-cd79-11e8-8a86-79a8ea0a2fdf.png)

Não seria o caso de rodar este comando antes de selecionar um novo projeto, assim ficando apenas o que foi selecionado no settings ?

vlw..

**Comment by AlencarGabriel** [comment]
Boa tarde, detectei este problema após a ultima release. Na verdade o que a extensão deveria fazer é deixar apenas um projeto no Workspace Settings, e agora está mantendo duas.

Por isso cada vez que o projeto é alterado esta mensagem aparece. Mais tarde vou fazer a correção e subo uma nova versão. 

Obrigado pelo Feedback ;)
